//登录状态
export const LOGIN_ING = 'LOGIN_ING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const RESET_LOGIN_STATE = 'RESET_LOGIN_STATE';

//诗歌模块
export const GETPOETRY_ING = 'GETPOETRY_ING';
export const GETPOETRY_SUCCESS = 'GETPOETRY_SUCCESS';
export const GETPOETRY_REFRESH_ING = 'GETPOETRY_REFRESH_ING';
export const GETPOETRY_REFRESH_SUCCESS = 'GETPOETRY_REFRESH_SUCCESS';
export const ADDDATA_ING = 'ADDDATA_ING';
export const ADDDATA_SUCCESS = 'ADDDATA_SUCCESS';
export const GETCOMMENT_ING = 'GETCOMMENT_ING';
export const GETCOMMENT_SUCCESS = 'GETCOMMENT_SUCCESS';

//观察模块
export const GETPICCATE_ING = 'GETPICCATE_ING';
export const GETPICCATE_SUCCESS = 'GETPICCATE_SUCCESS';

//算术模块
export const GETMATHCATE_ING = 'GETMATHCATE_ING';
export const GETMATHCATE_SUCCESS = 'GETMATHCATE_SUCCESS';

//日志模块
export const GETLOG_ING = 'GETLOG_ING';
export const GETLOG_SUCCESS = 'GETLOG_SUCCESS';
export const GETDIARY_ING = 'GETDIARY_ING';
export const GETDIARY_SUCCESS = 'GETDIARY_SUCCESS';
export const GETDIARY_FAIL = 'GETDIARY_FAIL';
